version: "3.9"

services:
  draco:
    image: ging/fiware-draco:2.1.0
    container_name: fiware-draco
    ports:
      - 8181:8181
      - 5050:5050
    networks:
      - fiware-network
    environment:
      - NIFI_WEB_HTTP_PORT=8181
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      - DRACO_DEBUG_LEVEL=INFO
      - DRACO_MONGO_SERVICE=mongo-draco
      - DRACO_MONGO_PORT=27017
      - FIWARE_SERVICE=default
      - FIWARE_SERVICEPATH=/
      - DRACO_MONGO_DB=sth_default

  orion:
    image: fiware/orion:3.10.1
    container_name: fiware-orion
    ports:
      - 1026:1026
    networks:
      - fiware-network
    depends_on:
      - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
    environment:
      - ORION_LOG_LEVEL=DEBUG

  mongo-db:
    image: mongo:4.4
    container_name: db-mongo
    ports:
      - 27017:27017
    networks:
      - fiware-network
    volumes:
      - mongo-data:/data/db
    command: --nojournal

  mongo-draco:
    image: mongo:4.4
    container_name: db-mongo-draco
    ports:
      - 27018:27017
    networks:
      - fiware-network
    volumes:
      - draco-data:/data/db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

    ports:
      - "3100:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'  

networks:
  fiware-network:
    driver: bridge

volumes:
  mongo-data:
  draco-data:
  grafana_storage: {}
  db-config:
  postgresdb:
